# Welcome to numpy

In [1]:
import numpy as np

In [2]:
arr=np.array([[3,4,5,6,7]],np.int32)

In [3]:
arr

array([[3, 4, 5, 6, 7]])

In [4]:
arr.shape

(1, 5)

In [5]:
arr.dtype

dtype('int32')

In [6]:
arr[0,2]=25

In [7]:
arr

array([[ 3,  4, 25,  6,  7]])

In [8]:
arr.size

5

In [9]:
np.array({55,44,55})

array({44, 55}, dtype=object)

In [10]:
myarr=np.array([[1,2,3,4],[6,7,3,2]],np.int64)

In [11]:
myarr.dtype

dtype('int64')

In [12]:
myarr.shape

(2, 4)

In [13]:
myarr.size

8

In [14]:
zeros=np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rng=np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace=np.linspace(1,5,12)

In [19]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [20]:
lsp=np.linspace(2,10,12)

In [21]:
lsp

array([ 2.        ,  2.72727273,  3.45454545,  4.18181818,  4.90909091,
        5.63636364,  6.36363636,  7.09090909,  7.81818182,  8.54545455,
        9.27272727, 10.        ])

In [22]:
emp=np.empty((4,6))

In [23]:
emp

array([[1.22439157e-311, 1.22536665e-311, 4.94065646e-324,
        4.03179200e-313, 4.99006302e-321, 1.22536665e-311],
       [9.54898106e-313, 1.22536665e-311, 4.94065646e-324,
        1.22536665e-311, 1.22536665e-311, 5.81021200e-321],
       [0.00000000e+000, 1.22439157e-311, 0.00000000e+000,
        5.77562740e-321, 0.00000000e+000, 1.22439157e-311],
       [1.22536665e-311, 5.77068674e-321, 0.00000000e+000,
        1.22439157e-311, 1.22536665e-311, 5.58294180e-321]])

In [24]:
emp_like=np.empty_like(lsp)

In [25]:
emp_like

array([ 2.        ,  2.72727273,  3.45454545,  4.18181818,  4.90909091,
        5.63636364,  6.36363636,  7.09090909,  7.81818182,  8.54545455,
        9.27272727, 10.        ])

In [26]:
ide=np.identity(45)

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
ide.shape

(45, 45)

In [29]:
arr=np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr=arr.ravel()

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [35]:
ar=np.array(x)

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [37]:
ar.sum()

29

In [38]:
ar.sum(axis=0)

array([12,  8,  9])

In [39]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [40]:
ar.T    #TRANSPORT 

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [41]:
  ar.flat

In [42]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [43]:
ar.ndim

2

In [44]:
ar.size

9

In [45]:
ar.nbytes

36

In [46]:
  one=np.array([1,2,3,4])

In [47]:
one

array([1, 2, 3, 4])

In [48]:
one.argmax(  )

3

In [49]:
one.argmin()

0

In [50]:
one.argsort()

array([0, 1, 2, 3], dtype=int64)

In [51]:
ar.argmax()

6

In [52]:
ar.argmin()

8

In [53]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [54]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [55]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [56]:
ajit=[[2,3,4],[5,6,7]]

In [57]:
lucky=np.array(ajit,np.int64)

In [58]:
lucky

array([[2, 3, 4],
       [5, 6, 7]], dtype=int64)

In [59]:
lucky.ravel()

array([2, 3, 4, 5, 6, 7], dtype=int64)

In [60]:
A=np.array([[1,2,1],
           [4,0,6],
           [16,1,0]])

In [61]:
[324,34]+[34,546]

[324, 34, 34, 546]

In [62]:
B=np.array([[1,2,1],
           [4,0,6],
           [8,1,0]])

In [63]:
A*B

array([[  1,   4,   1],
       [ 16,   0,  36],
       [128,   1,   0]])

In [64]:
np.sqrt(A)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [4.        , 1.        , 0.        ]])

In [65]:
np.where(A>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [66]:
np.count_nonzero(A)

7

In [68]:
np.nonzero(B)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1], dtype=int64))

In [69]:
import sys

In [70]:
cha=[0,4,55,2]

In [71]:
np_a=np.array(cha)

In [72]:
sys.getsizeof(1)*len(cha)

112

In [75]:
np_a.itemsize*np_a.size

16